"""Explicit mutual TLS identities and method grants for device transports.

Private keys are supplied by the operator, never generated by core or included
in public identities. Certificate rotation requires a newly configured context.
OS isolation must keep these keys away from untrusted candidate/model code.
"""

from copy import deepcopy
from dataclasses import dataclass
import hashlib
from pathlib import Path
import re
import ssl
from types import MappingProxyType

from ..storage import file_digest


def fingerprint(certificate):
    return hashlib.sha256(certificate).hexdigest()


def certificate_fingerprint(path):
    pem = Path(path).read_text()
    match = re.search(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----", pem, re.S)
    if not match:
        raise ValueError("Expected a PEM certificate")
    return fingerprint(ssl.PEM_cert_to_DER_cert(match.group()))


def _pin(value):
    if not isinstance(value, str) or not re.fullmatch(r"[0-9a-f]{64}", value):
        raise ValueError("Expected a lowercase SHA-256 certificate fingerprint")
    return value


def _context(ca, certificate, private_key, *, server):
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER if server else ssl.PROTOCOL_TLS_CLIENT)
    context.minimum_version = ssl.TLSVersion.TLSv1_2
    context.verify_mode = ssl.CERT_REQUIRED
    context.check_hostname = not server
    if not server:
        context.hostname_checks_common_name = False
    context.load_verify_locations(cafile=str(ca))
    # Never fall back to OpenSSL's interactive password prompt in a service.
    context.load_cert_chain(str(certificate), str(private_key), password=lambda: b"")
    return context


@dataclass(frozen=True)
class ClientTLS:
    ca: str
    certificate: str
    private_key: str
    server_sha256: str

    def __post_init__(self):
        _pin(self.server_sha256)
        object.__setattr__(self, "context", _context(self.ca, self.certificate, self.private_key, server=False))
        object.__setattr__(self, "_public", dict(schema="physicalrsi.mutual-tls-client/v1",
            ca_sha256=file_digest(Path(self.ca)), client_sha256=certificate_fingerprint(self.certificate),
            server_sha256=self.server_sha256, minimum_version="TLSv1.2", hostname_verification=True,
            openssl=ssl.OPENSSL_VERSION))

    def identity(self):
        return deepcopy(self._public)


@dataclass(frozen=True)
class PeerGrant:
    principal: str
    methods: tuple[str, ...]

    def __post_init__(self):
        if not isinstance(self.principal, str) or not self.principal.strip():
            raise ValueError("Declare an authenticated principal name")
        if (not isinstance(self.methods, (list, tuple)) or not self.methods or
                any(not isinstance(method, str) or not re.fullmatch(r"[a-zA-Z0-9_.]+", method) for method in self.methods)):
            raise ValueError("Declare exact RPC method grants; wildcards are not accepted")
        methods = tuple(sorted(set(self.methods)))
        object.__setattr__(self, "methods", methods)


@dataclass(frozen=True)
class ServerTLS:
    ca: str
    certificate: str
    private_key: str
    peers: dict
    read_seconds: float = 5
    request_bytes: int = 1024 * 1024
    max_connections: int = 32

    def __post_init__(self):
        from ...timing import finite_seconds
        finite_seconds(self.read_seconds)
        if (type(self.request_bytes) is not int or self.request_bytes <= 0 or
                type(self.max_connections) is not int or self.max_connections <= 0):
            raise ValueError("Positive request and connection limits required")
        peers = {_pin(key): value if isinstance(value, PeerGrant) else PeerGrant(**value)
                 for key, value in self.peers.items()}
        if not peers:
            raise ValueError("Mutual TLS requires explicitly allowed client certificates")
        object.__setattr__(self, "peers", MappingProxyType(peers))
        object.__setattr__(self, "context", _context(self.ca, self.certificate, self.private_key, server=True))
        object.__setattr__(self, "_public", dict(schema="physicalrsi.mutual-tls-server/v1",
            ca_sha256=file_digest(Path(self.ca)), server_sha256=certificate_fingerprint(self.certificate),
            peers={key: dict(principal=value.principal, methods=list(value.methods)) for key, value in sorted(peers.items())},
            minimum_version="TLSv1.2", read_seconds=self.read_seconds, request_bytes=self.request_bytes,
            max_connections=self.max_connections, openssl=ssl.OPENSSL_VERSION))

    def identity(self):
        return deepcopy(self._public)
